services:
  api:
    image: cesizen-api:latest
    container_name: cesizen-api-dev

    ports:
      - "3001:3000"

    env_file:
      - .env

    depends_on:
      - db

    networks:
      - cesizen-api_default

    restart: unless-stopped

  db:
    image: postgres:16
    container_name: cesizen-db-dev

    environment:
      POSTGRES_USER: cesizen
      POSTGRES_PASSWORD: cesizen
      POSTGRES_DB: cesizen_dev

    volumes:
      - cesizen_pgdata_dev:/var/lib/postgresql/data

    networks:
      - cesizen-api_default

    restart: unless-stopped

volumes:
  cesizen_pgdata_dev:

networks:
  cesizen-api_default:
    driver: bridge

