services:
  db:
    image: postgres:16
    container_name: cesizen-postgres
    environment:
      POSTGRES_USER: cesizen
      POSTGRES_PASSWORD: cesizen
      POSTGRES_DB: cesizen_db
    ports:
      - "5434:5432"
    volumes:
      - cesizen_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: cesizen-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cesizen.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  cesizen_pgdata:
