name: CI API

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation des dépendances
        run: npm ci

      - name: Génération Prisma Client
        run: npx prisma generate

      - name: Build de l'API
        run: npm run build

      - name: Tests API
        run: npm run test

      - name: Audit sécurité
        run: npm audit --audit-level=critical